### ISSUE TITLE
how to support headless mode?

### ISSUE THREAD

**Issue by baikeh** [Tencent/TencentKona-8#4] opened 2019-11-13 07:49 UTC
`-Djava.awt.headless=true` not work

**Comment by IamYangxf** [comment] 2019-11-13 09:13
Hi Baikeh, thanks for your feedback. Could you provide the detail reproduce steps, environments, configuration and symptom? 
Kona team has verified with Oracle official guide on headless mode, see https://www.oracle.com/technical-resources/articles/javase/headless.html. But it passed.
Thank you very much!

**Comment by linzang** [comment] 2019-11-18 12:15
Dear @baikeh, 
     would you like to share your reproducer? so that we can check what is the problem. 
     Thanks!
BRs,
Lin

**Comment by linzang** [comment] 2020-12-16 03:25
I will close this issue since there is no update.

**Closed by linzang** 2020-12-16 03:25 UTC
